### ISSUE TITLE
anitor-stream crashes on windows

### ISSUE THREAD

**Issue by Narixv** [gan-of-culture/anitor-stream#1]
**My System**

```
Processor	Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz   2.11 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor
Edition		Windows 10 Pro
Version		21H2
Installed on	‎11/‎09/‎2021
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0
```
**anitor-stream Version**
```
Jan 11, 2022	v1.0.1
```
- On the README for `anitor-stream` it says to install the one dependency as the prerequisite `webtorrent-cli`
- However I am on a windows based system and see support was recently added.
- When I downloaded the assets I need and run them I get the **Observed Behavior** below

**Observed Behavior**

1. I am greeted with the `"aired in the last 24 hours"` dialog.
2. I enter the following command in order to initiate a search query...
```
 anitor-stream Girls Und Panzer -p vlc
```
3. `anitor-stream` crashes

https://user-images.githubusercontent.com/103471431/162867145-d5d33acd-3860-4565-abbe-e11d965c62f6.mp4

**Comment by gan-of-culture** [comment]
you don't have to do start anitor-stream.exe. Move in your directory and just try it like this `.\anitor-stream.exe "Girls und Panzer" -p vlc`

**Comment by Narixv** [comment]
> you don't have to do start anitor-stream.exe. Move in your directory and just try it like this `.\anitor-stream.exe "Girls und Panzer" -p vlc`

Got it ok, So I understand now.

However, is `anitor-stream` supposed to open VLC to start the stream? I'm not sure what the expected behavior is supposed to be.

Thank you,

**Comment by gan-of-culture** [comment]
yes vlc should open, but vlc.exe has to be in your Windows PATH. Just add the folder your vlc.exe is in right now to the PATH that's probably the easiest way to get it to work.

**Comment by Narixv** [comment]
I am sorry,

I'm confused by the explanation you gave me. I added the `"VLC"` directory to the `"Windows (C:)"` directory and I ran the command again and got the same result.

I am not sure if I am doing something wrong, or if I am just missing some context.

I sincerely apologize,

https://user-images.githubusercontent.com/103471431/163230645-36c2f773-b2d3-4b8b-96f0-864d69997446.mp4

**Comment by gan-of-culture** [comment]
Hi! No worries. You have to follow this guide [https://stackoverflow.com/questions/44272416/how-to-add-a-folder-to-path-environment-variable-in-windows-10-with-screensho](https://stackoverflow.com/questions/44272416/how-to-add-a-folder-to-path-environment-variable-in-windows-10-with-screensho) to add the path you installed VLC.exe to the Windows PATH. It's like a windows setting.

To check if it's working you can open up a terminal anywhere and type `vlc` and it should open the vlc player.
