### ISSUE TITLE
I can't load the  libssl.so.3 file.

### ISSUE THREAD

**Issue by Shubham-C12** [gan-of-culture/anitor-stream#2]
I got this error message when I tried to run the Anitor.
./anitor-stream: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

MyOS: ubuntu 20.04
Openssl is installled and up to date

**Comment by gan-of-culture** [comment]
Hi,

did you build the executable yourself or did you download the one from the release? If you have rust installed please try running it using ```cargo r "One Piece"```.

**Comment by Shubham-C12** [comment]
![Screenshot 2024-06-12 230805](https://github.com/gan-of-culture/anitor-stream/assets/85118508/66c93663-8475-40f1-a456-fc7eea835519)
`Cargo r [anime]` is not working. I have attached a screenshot showing the problem. After checking that Error I installed the `pkg-config`. And It's still not working.

**Comment by gan-of-culture** [comment]
Looks like an error with your system to me. You might need to trouble shoot it with people from the rust project. Unfortunately I don't think I can help you here.

**Comment by Shubham-C12** [comment]
I don't know bro, I just spinned that VM up from azure. Ubuntu 20.04LTS is my os. It's okay if you can't help me.

**Comment by Shubham-C12** [comment]
I found a fix for this maybe it will help someone in the future. So I reopened the issue.

- First you need to find the file called `openssl.cnf` on your machine. For me it was here `/etc/ssl/openssl.cnf`
- Then use this: `export PKG_CONFIG_PATH=/path/to/openssl.cnf/pkgconfig:$PKG_CONFIG_PATH` edit the `/path/to/openssl.cnf`
- After that you are pretty much done, Just verify it by `pkg-config --libs --cflags openssl`
If you get a output like this in the photograph you are pretty much done.
![Screenshot 2024-06-15 002545](https://github.com/gan-of-culture/anitor-stream/assets/85118508/abf5eb34-1867-4157-9bc4-975e2cab5fee)

- Now just build the anitor from the source code and done!
